export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
//AUTH
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_SMS_CODE_SENT = 'LOGIN_SMS_CODE_SENT';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const VERIFY_PENDING = 'VERIFY_PENDING';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const VERIFY_FAIL = 'VERIFY_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SET_TOKEN_PENDING = 'SET_TOKEN_PENDING';
export const SET_TOKEN_SUCCESS = 'SET_TOKEN_SUCCESS';
export const SET_TOKEN_FAIL = 'SET_TOKEN_FAIL';
export const FIRST_TIME_SUCCESS = 'FIRST_TIME_SUCCESS';

//FIREBASE
export const ADD_FCMTOKEN_PENDING = 'ADD_FCMTOKEN_PENDING';
export const ADD_FCMTOKEN_SUCCESS = 'ADD_FCMTOKEN_SUCCESS';
export const ADD_FCMTOKEN_ERROR = 'ADD_FCMTOKEN_ERROR';
// USER
export const GET_USER_PENDING = 'GET_USER_PENDING';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const SET_USER_PENDING = 'SET_USER_PENDING';
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS';
export const SET_USER_ERROR = 'SET_USER_ERROR';

export const UPDATE_PROFILE_PENDING = 'UPDATE_PROFILE_PENDING';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

export const SET_USER_IMAGE_PENDING = 'SET_USER_IMAGE_PENDING';
export const SET_USER_IMAGE_SUCCESS = 'SET_USER_IMAGE_SUCCESS';
export const SET_USER_IMAGE_ERROR = 'SET_USER_IMAGE_ERROR';
//ORG
export const FIND_ORGANISATION_PENDING = 'FIND_ORGANISATION_PENDING';
export const FIND_ORGANISATION_SUCCESS = 'FIND_ORGANISATION_SUCCESS';
export const FIND_ORGANISATION_FAIL = 'FIND_ORGANISATION_FAIL';

export const CONFIRM_ORGANISATION_PENDING = 'CONFIRM_ORGANISATION_PENDING';
export const CONFIRM_ORGANISATION_SUCCESS = 'CONFIRM_ORGANISATION_SUCCESS';
export const CONFIRM_ORGANISATION_FAIL = 'CONFIRM_ORGANISATION_FAIL';

export const GET_USER_GROUPS_OF_ORG_PENDING = 'GET_USER_GROUPS_OF_ORG_PENDING';
export const GET_USER_GROUPS_OF_ORG_SUCCESS = 'GET_USER_GROUPS_OF_ORG_SUCCESS';
export const GET_USER_GROUPS_OF_ORG_FAIL = 'GET_USER_GROUPS_OF_ORG_FAIL';

export const LEAVE_ORGANISATION_PENDING = 'LEAVE_ORGANISATION_PENDING';
export const LEAVE_ORGANISATION_SUCCESS = 'LEAVE_ORGANISATION_SUCCESS';
export const LEAVE_ORGANISATION_FAIL = 'LEAVE_ORGANISATION_FAIL';

export const LEAVE_GROUP_OF_ORGANISATION_PENDING = 'LEAVE_GROUP_OF_ORGANISATION_PENDING';
export const LEAVE_GROUP_OF_ORGANISATION_SUCCESS = 'LEAVE_GROUP_OF_ORGANISATION_SUCCESS';
export const LEAVE_GROUP_OF_ORGANISATION_FAIL = 'LEAVE_GROUP_OF_ORGANISATION_FAIL';
//FEIDE
export const FEIDE_VERIFICATION_PENDING = 'FEIDE_VERIFICATION_PENDING';
export const FEIDE_VERIFICATION_SUCCESS = 'FEIDE_VERIFICATION_SUCCESS';
export const FEIDE_VERIFICATION_FAIL = 'FEIDE_VERIFICATION_FAIL';

// GROUPS
export const GET_GROUPS_PENDING = 'GET_GROUPS_PENDING';
export const GET_GROUPS_SUCCESS = 'GET_GROUPS_SUCCESS';
export const GET_GROUPS_FAIL = 'GET_GROUPS_FAIL';

export const GET_DETAILS_GROUP_PENDING = 'GET_DETAILS_GROUP_PENDING';
export const GET_DETAILS_GROUP_SUCCESS = 'GET_DETAILS_GROUP_SUCCESS';
export const GET_DETAILS_GROUP_FAIL = 'GET_DETAILS_GROUP_FAIL';

export const SAVED_GROUPS_PENDING = 'SAVED_GROUPS_PENDING';
export const SAVED_GROUPS_SUCCESS = 'SAVED_GROUPS_SUCCESS';
export const SAVED_GROUPS_FAIL = 'SAVED_GROUPS_FAIL';

export const UPDATE_GROUPS_PENDING = 'UPDATE_GROUPS_PENDING';
export const UPDATE_GROUPS_SUCCESS = 'UPDATE_GROUPS_SUCCESS';
export const UPDATE_GROUPS_FAIL = 'UPDATE_GROUPS_FAIL';

export const REMOVE_GROUPS_PENDING = 'REMOVE_GROUPS_PENDING';
export const REMOVE_GROUPS_SUCCESS = 'REMOVE_GROUPS_SUCCESS';
export const REMOVE_GROUPS_FAIL = 'REMOVE_GROUPS_FAIL';

export const GET_GROUPS_FOR_USER_PENDING = 'GET_GROUPS_FOR_USER_PENDING';
export const GET_GROUPS_FOR_USER_SUCCESS = 'GET_GROUPS_FOR_USER_SUCCESS';
export const GET_GROUPS_FOR_USER_FAIL = 'GET_GROUPS_FOR_USER_FAIL';

// activity
export const CREATE_EVENT_PENDING = 'CREATE_EVENT_PENDING';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAIL = 'CREATE_EVENT_FAIL';

export const GET_INIT_EVENT_PENDING = 'GET_INIT_EVENT_PENDING';
export const GET_INIT_EVENT_SUCCESS = 'GET_INIT_EVENT_SUCCESS';
export const GET_INIT_EVENT_FAIL = 'GET_INIT_EVENT_FAIL';

export const GET_INIT_LIST_PENDING = 'GET_INIT_LIST_PENDING';
export const GET_INIT_LIST_SUCCESS = 'GET_INIT_LIST_SUCCESS';
export const GET_INIT_LIST_FAIL = 'GET_INIT_LIST_FAIL';

export const GET_ALL_EVENTS_WITH_FILTER_PENDING = 'GET_ALL_EVENTS_WITH_FILTER_PENDING';
export const GET_ALL_EVENTS_WITH_FILTER_SUCCESS = 'GET_ALL_EVENTS_WITH_FILTER_SUCCESS';
export const GET_ALL_EVENTS_WITH_FILTER_FAIL = 'GET_ALL_EVENTS_WITH_FILTER_FAIL';

export const GET_MY_EVENTS_WITH_FILTER_PENDING = 'GET_MY_EVENTS_WITH_FILTER_PENDING';
export const GET_MY_EVENTS_WITH_FILTER_SUCCESS = 'GET_MY_EVENTS_WITH_FILTER_SUCCESS';
export const GET_MY_EVENTS_WITH_FILTER_FAIL = 'GET_MY_EVENTS_WITH_FILTER_FAIL';

export const GET_MY_SPONSOR_EVENTS_PENDING = 'GET_MY_SPONSOR_EVENTS_PENDING';
export const GET_MY_SPONSOR_EVENTS_SUCCESS = 'GET_MY_SPONSOR_EVENTS_SUCCESS';
export const GET_MY_SPONSOR_EVENTS_FAIL = 'GET_MY_SPONSOR_EVENTS_FAIL';

export const UPDATE_EVENT_PENDING = 'UPDATE_EVENT_PENDING';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAIL = 'UPDATE_EVENT_FAIL';

export const CANCEL_EVENT_PENDING = 'CANCEL_EVENT_PENDING';
export const CANCEL_EVENT_SUCCESS = 'CANCEL_EVENT_SUCCESS';
export const CANCEL_EVENT_FAIL = 'CANCEL_EVENT_FAIL';

export const DELETE_EVENT_PENDING = 'DELETE_EVENT_PENDING';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAIL = 'DELETE_EVENT_FAIL';

export const REPORT_EVENT_PENDING = 'REPORT_EVENT_PENDING';
export const REPORT_EVENT_SUCCESS = 'REPORT_EVENT_SUCCESS';
export const REPORT_EVENT_FAIL = 'REPORT_EVENT_FAIL';

export const GET_FOR_USER_PENDING = 'GET_FOR_USER_PENDING';
export const GET_FOR_USER_SUCCESS = 'GET_FOR_USER_SUCCESS';
export const GET_FOR_USER_FAIL = 'GET_FOR_USER_FAIL';

export const UPDATE_SHORTCUTE_PENDING = 'UPDATE_SHORTCUTE_PENDING';
export const UPDATE_SHORTCUTE_SUCCESS = 'UPDATE_SHORTCUTE_SUCCESS';
export const UPDATE_SHORTCUTE_FAIL = 'UPDATE_SHORTCUTE_FAIL';

export const GET_SHORTCUTE_PENDING = 'GET_SHORTCUTE_PENDING';
export const GET_SHORTCUTE_SUCCESS = 'GET_SHORTCUTE_SUCCESS';
export const GET_SHORTCUTE_FAIL = 'GET_SHORTCUTE_FAIL';

export const DELETE_SHORTCUTE_PENDING = 'DELETE_SHORTCUTE_PENDING';
export const DELETE_SHORTCUTE_SUCCESS = 'DELETE_SHORTCUTE_SUCCESS';
export const DELETE_SHORTCUTE_FAIL = 'DELETE_SHORTCUTE_FAIL';

export const GET_ACTIVITY_DETAIL = 'GET_ACTIVITY_DETAIL';
export const ACTIVITY_DETAIL_SUCCESS = 'ACTIVITY_DETAIL_SUCCESS';
export const ACTIVITY_DETAIL_FAIL = 'ACTIVITY_DETAIL_FAIL';
export const GET_COMMENT_PENDING = 'GET_COMMENT_PENDING';
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS';
export const GET_COMMENT_FAIL = 'GET_COMMENT_FAIL';

// commments
export const ADD_COMMENT_PENDING = 'ADD_COMMENT_PENDING';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = ' ADD_COMMENT_FAIL';

export const DELETE_COMMENT_PENDING = 'DELETE_COMMENT_PENDING';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';

export const REPORT_COMMENT_PENDING = ' REPORT_COMMENT_PENDING';
export const REPORT_COMMENT_SUCCESS = 'REPORT_COMMENT_SUCCESS';
export const REPORT_COMMENT_FAIL = 'REPORT_COMMENT_FAIL';

export const UPDATE_COMMENT_PENDING = 'UPDATE_COMMENT_PENDING';
export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS';
export const UPDATE_COMMENT_FAIL = 'UPDATE_COMMENT_FAIL';

export const NO_INTERENT = 'NO_INTERENT';
export const INTERENT = 'INTERENT';

export const INIT_LIST_CLEAR = 'INIT_LIST_CLEAR';