require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'


target 'JoinMe' do
   # React Native Maps dependencies
   rn_maps_path = '../node_modules/react-native-maps'
   # add the Firebase pod for Google Analytics
   pod 'Firebase/Analytics'
   pod 'react-native-google-maps', :path => rn_maps_path
   pod 'GoogleMaps'
   pod 'Google-Maps-iOS-Utils'
   pod 'Permission-Notifications', :path => '../node_modules/react-native-permissions/ios/Notifications'
   
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'RNOpenAppSettings', :path => '../node_modules/react-native-app-settings'

  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  target 'JoinMeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.74.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'JoinMe-tvOS' do
  # Pods for JoinMe-tvOS

  target 'JoinMe-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
